name: CI/CD - React + Vite + Tailwind

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # =========================
  # 1. Quality Check (Lint + Test + Build)
  # =========================
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          if [ -f package.json ] && grep -q '"lint"' package.json; then
            npm run lint
          else
            echo "No lint script found, skipping..."
          fi

      - name: Run Tests
        run: |
          if [ -f package.json ] && grep -q '"test"' package.json; then
            npm test -- --watchAll=false
          else
            echo "No test script found, skipping..."
          fi

      - name: Build project
        run: npm run build

      - name: Upload production-ready build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist